#!/usr/bin/env bash
set -euo pipefail

TARGET_DIR="${1:-$(pwd)}"
GITIGNORE_PATH="$TARGET_DIR/.gitignore"

if [[ ! -d "$TARGET_DIR" ]]; then
  echo "Target directory does not exist: $TARGET_DIR" >&2
  exit 1
fi

mkdir -p "$TARGET_DIR"
touch "$GITIGNORE_PATH"

ensure_line() {
  local line="$1"

  if ! grep -Fqx "$line" "$GITIGNORE_PATH"; then
    printf '%s\n' "$line" >> "$GITIGNORE_PATH"
  fi
}

if [[ -s "$GITIGNORE_PATH" ]] && [[ "$(tail -c 1 "$GITIGNORE_PATH")" != "" ]]; then
  printf '\n' >> "$GITIGNORE_PATH"
fi

ensure_line "# Harness collaboration docs (generated by harness:init)"
ensure_line "docs/superpowers/"
ensure_line "artifacts/"
ensure_line "/*.md"
ensure_line "!/AGENTS.md"
ensure_line "!/README.md"

if git -C "$TARGET_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git -C "$TARGET_DIR" rm --cached -r --ignore-unmatch \
    PROGRESS.md \
    MEMORY.md \
    NEXT_STEP.md \
    docs/superpowers \
    artifacts \
    >/dev/null
fi
